blank_issues_enabled: true
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/GingerGraham/bash-logger/blob/main/bash_logging.md
    about: Check the documentation for usage instructions and examples
