name: Linting
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install ShellCheck
        run: |
          python -m pip install --upgrade pip
          python -m pip install shellcheck-py==0.11.0.1
          shellcheck --version
      - name: Run ShellCheck
        run: find . -name '*.sh' -print0 | xargs -0 shellcheck --severity=warning --external-sources

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install MarkdownLint
        run: |
          sudo apt-get install npm
          sudo npm install -g markdownlint-cli
      - name: Run MarkdownLint
        run: markdownlint **/*.md
